### PR TITLE
Changed Mappings and updated README. Fix slight issue with ISBN for bookInfo

### LINKED ISSUE #17: change update and delete to putmapping and deletemapping
putmapping

_Originally posted by @Yichi-liu in https://github.com/BookCooper/TheBookCooper/pull/16#discussion_r1502039468_

### PR DESCRIPTION
**Pull request by Yichi-liu**
I changed mappings for update and delete so now it should be clearer.

I updated README to test all the functionality easier. I also found a slight bug for book Info:
if you input a number that is less than a long, then the number would then be considered as an integer. So I added a check since some ISBN numbers are 13 digits and some are 10 digits.

### CODE REVIEW

File: src/main/java/com/thebookcooper/controller/BookInfoController.java [hunk 1]
```diff
@@ -39,14 +41,22 @@ public Book createBook(@RequestBody String json) throws JsonProcessingException
...
             newBook.setTitle((String) inputMap.get("title"));
-            newBook.setISBN((long) inputMap.get("isbn"));
             //newBook.setPublishDate(Date.valueOf(LocalDate.now())); <-- set the date to be the current day
             newBook.setPublishDate(Date.valueOf((String) inputMap.get("publishDate"))); //date has to be of form "YYYY-MM-DD"
             newBook.setAuthor((String) inputMap.get("author"));
             newBook.setGenre((String) inputMap.get("genre"));
             newBook.setBookCondition((String) inputMap.get("bookCondition"));
             newBook.setPrice((double) inputMap.get("price"));
 
+            Object isbnObject = inputMap.get("isbn");
```
Comment (Aidan4478D) [inline src/main/java/com/thebookcooper/controller/BookInfoController.java:51]: good idea to avoid the strange error

File: README.md
Comment (Aidan4478D) [inline README.md:1]: we're gonna end up having a lot of DAO's to test and that may clutter the README so do you think we should have something like a link that goes to a different README file or similar that has all of the body's of each dao to send? this way it doesn't make the main README big big

**Review by Aidan4478D — APPROVED** [review]
good changes, look at comment for potential improvement to README
